# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\MinGW\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\MinGW\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Cristian Polisi\CLionProjects\Prova"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Cristian Polisi\CLionProjects\Prova"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	C:\MinGW\mingw64\bin\ctest.exe --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\MinGW\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\MinGW\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	C:\MinGW\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	C:\MinGW\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	C:\MinGW\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	C:\MinGW\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	C:\MinGW\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	C:\MinGW\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Cristian Polisi\CLionProjects\Prova\CMakeFiles" "C:\Users\Cristian Polisi\CLionProjects\Prova\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Cristian Polisi\CLionProjects\Prova\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Prova

# Build rule for target.
Prova: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Prova
.PHONY : Prova

# fast build rule for target.
Prova/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/build
.PHONY : Prova/fast

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\runTests.dir\build.make CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest\googlemock\CMakeFiles\gmock.dir\build.make _deps/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest\googlemock\CMakeFiles\gmock_main.dir\build.make _deps/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest\googletest\CMakeFiles\gtest.dir\build.make _deps/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest\googletest\CMakeFiles\gtest_main.dir\build.make _deps/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

ContoCorrente.obj: ContoCorrente.cpp.obj
.PHONY : ContoCorrente.obj

# target to build an object file
ContoCorrente.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/ContoCorrente.cpp.obj
.PHONY : ContoCorrente.cpp.obj

ContoCorrente.i: ContoCorrente.cpp.i
.PHONY : ContoCorrente.i

# target to preprocess a source file
ContoCorrente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/ContoCorrente.cpp.i
.PHONY : ContoCorrente.cpp.i

ContoCorrente.s: ContoCorrente.cpp.s
.PHONY : ContoCorrente.s

# target to generate assembly for a file
ContoCorrente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/ContoCorrente.cpp.s
.PHONY : ContoCorrente.cpp.s

Entrata.obj: Entrata.cpp.obj
.PHONY : Entrata.obj

# target to build an object file
Entrata.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Entrata.cpp.obj
.PHONY : Entrata.cpp.obj

Entrata.i: Entrata.cpp.i
.PHONY : Entrata.i

# target to preprocess a source file
Entrata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Entrata.cpp.i
.PHONY : Entrata.cpp.i

Entrata.s: Entrata.cpp.s
.PHONY : Entrata.s

# target to generate assembly for a file
Entrata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Entrata.cpp.s
.PHONY : Entrata.cpp.s

Transazione.obj: Transazione.cpp.obj
.PHONY : Transazione.obj

# target to build an object file
Transazione.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Transazione.cpp.obj
.PHONY : Transazione.cpp.obj

Transazione.i: Transazione.cpp.i
.PHONY : Transazione.i

# target to preprocess a source file
Transazione.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Transazione.cpp.i
.PHONY : Transazione.cpp.i

Transazione.s: Transazione.cpp.s
.PHONY : Transazione.s

# target to generate assembly for a file
Transazione.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Transazione.cpp.s
.PHONY : Transazione.cpp.s

Uscita.obj: Uscita.cpp.obj
.PHONY : Uscita.obj

# target to build an object file
Uscita.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Uscita.cpp.obj
.PHONY : Uscita.cpp.obj

Uscita.i: Uscita.cpp.i
.PHONY : Uscita.i

# target to preprocess a source file
Uscita.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Uscita.cpp.i
.PHONY : Uscita.cpp.i

Uscita.s: Uscita.cpp.s
.PHONY : Uscita.s

# target to generate assembly for a file
Uscita.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/Uscita.cpp.s
.PHONY : Uscita.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/main.cpp.s
.PHONY : main.cpp.s

test/test_main.obj: test/test_main.cpp.obj
.PHONY : test/test_main.obj

# target to build an object file
test/test_main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/test/test_main.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\runTests.dir\build.make CMakeFiles/runTests.dir/test/test_main.cpp.obj
.PHONY : test/test_main.cpp.obj

test/test_main.i: test/test_main.cpp.i
.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/test/test_main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\runTests.dir\build.make CMakeFiles/runTests.dir/test/test_main.cpp.i
.PHONY : test/test_main.cpp.i

test/test_main.s: test/test_main.cpp.s
.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Prova.dir\build.make CMakeFiles/Prova.dir/test/test_main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\runTests.dir\build.make CMakeFiles/runTests.dir/test/test_main.cpp.s
.PHONY : test/test_main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... Prova
	@echo ... gmock
	@echo ... gmock_main
	@echo ... gtest
	@echo ... gtest_main
	@echo ... runTests
	@echo ... ContoCorrente.obj
	@echo ... ContoCorrente.i
	@echo ... ContoCorrente.s
	@echo ... Entrata.obj
	@echo ... Entrata.i
	@echo ... Entrata.s
	@echo ... Transazione.obj
	@echo ... Transazione.i
	@echo ... Transazione.s
	@echo ... Uscita.obj
	@echo ... Uscita.i
	@echo ... Uscita.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... test/test_main.obj
	@echo ... test/test_main.i
	@echo ... test/test_main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

